name = "Create Server"
author = "OwO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8c767235c544e03ab171cf7ed2e3adeceacf3ee9932399019d69327d02142d7"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
