name = "Create Server"
author = "OwO"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65ac9514117374632a0b7b60cfb34c871878ee69f6abef3034f567a3868c586c"

[versions]
minecraft = "1.21.1"
neoforge = "21.11.42"
